---
version: 2

run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-dirs-use-default: false

linters:
  enable:
    - errcheck
    - unused
    - ineffassign
    - staticcheck
    - gosec
    - gocritic
    - gocyclo
