repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        # Format each passed Go file and re-stage it if it's not ignored.
        entry: bash -c 'for f; do [ -e "$f" ] || continue; gofmt -s -w "$f"; if ! git check-ignore -q -- "$f"; then git add -- "$f"; fi; done' --
        language: system
        pass_filenames: true
        types: [go]
        files: '\.go$'

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run ./...
        language: system
        pass_filenames: false

      - id: go-test
        name: go test
        entry: bash -c 'go test ./...'
        language: system
        pass_filenames: false
