repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -s -w
        language: system
        types: [go]
        files: '\.go$'

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run ./...
        language: system
        pass_filenames: false

      - id: go-test
        name: go test
        entry: bash -c 'go test ./...'
        language: system
        pass_filenames: false
