{
 "title": "Media Server",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(plays_total, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(plays_total{job=~\"$job\"}, instance)"
   },
   {
    "name": "server",
    "label": "server",
    "query": "label_values(plays_total{job=~\"$job\", instance=~\"$instance\"}, server)"
   }
  ]
 },
 "panels": [
  {
   "title": "$server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server",
   "targets": [
    {}
   ]
  },
  {
   "title": "Platform Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "server_info{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}",
     "legendFormat": "{{platform}} - {{platform_version}}"
    }
   ]
  },
  {
   "title": "Host CPU Utilization by Server",
   "type": "stat",
   "description": "Only available on Plex servers with PlexPass",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "host_cpu_util{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Library Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(library_duration_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}) by (library)",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "Plex Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "server_info{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Host Memory Utilization by Server",
   "type": "stat",
   "description": "Only available on Plex servers with PlexPass",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "host_mem_util{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Library Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(library_storage_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}) by (library)",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "Library Items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(plex_library_items{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}) by (library)",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "Network"
    },
    {
     "expr": "rate(estimated_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "Network Est."
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[24h])) by (library_type)",
     "legendFormat": "{{library_type}}"
    }
   ]
  },
  {
   "title": "Duration by day of week",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__interval])) by (media_type) * ignoring(day,dow) group_right\n\n label_replace(   \n label_replace(   \n label_replace(   \n label_replace(   \n label_replace(   \n label_replace(      \n label_replace(   \n count_values without() (\"day\", day_of_week(timestamp(\n      sum(increase(          \n         play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}          \n      [$__interval]))  by (media_type)\n    )\n  ))\n  ,\"dow\",\"Sunday\",\"day\",\"0\")\n  ,\"dow\",\"Monday\",\"day\",\"1\")\n  ,\"dow\",\"Tuesday\",\"day\",\"2\")\n  ,\"dow\",\"Wednesday\",\"day\",\"3\")\n  ,\"dow\",\"Thursday\",\"day\",\"4\")\n  ,\"dow\",\"Friday\",\"day\",\"5\")\n  ,\"dow\",\"Saturday\",\"day\",\"6\")\n"
    }
   ]
  },
  {
   "title": "Total Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_media_movies{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Total Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_media_episodes{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Total Music Tracks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_media_music{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Total Photos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_media_photos{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Total Home Videos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "plex_media_other_videos{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Duration by hour of day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__interval])) by (media_type) * ignoring(hour) group_right\n    count_values without() (\"hour\", hour(timestamp(\n      sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__interval]))  by (media_type)\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Top 10 Titles by duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__interval])) by (media_type, title)",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Top 10 Users by duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__interval])) by (media_type, user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Top 10 Platforms by duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"}[$__interval])) by (media_type, device_type)",
     "legendFormat": "{{device_type}}"
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration by source resolution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(\n  label_replace(\n  label_replace(\n      play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\",stream_type!=\"\"}\n  , \"res\", \"$1\", \"stream_file_resolution\", \"(.*)\")\n  , \"res\", \"${1}p\", \"stream_file_resolution\", \"^([0-9]+)$\")\n  \n[$__interval:])) by (stream_type, res)\n",
     "legendFormat": "{{res}}"
    }
   ]
  },
  {
   "title": "Duration by streamed resolution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(\n  label_replace(\n  label_replace(\n      play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\",stream_type!=\"\"}\n  , \"res\", \"$1\", \"stream_resolution\", \"(.*)\")\n  , \"res\", \"${1}p\", \"stream_resolution\", \"^([0-9]+)$\")\n  \n[$__interval:])) by (stream_type, res)\n",
     "legendFormat": "{{res}}"
    }
   ]
  }
 ]
}